apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  app-config.yaml: |
    app:
      name: 云计算课程设计
      version: v1.0
      author: 黄金
      student_id: 2023112511
    redis:
      host: redis-svc
      port: 6379
    feature:
      enable_persistence: true
      enable_metrics: false